### ISSUE TITLE
Kubernetes Cluster Available - helper method

### ISSUE THREAD

**Issue by BertR** [ionos-cloud/sdk-go#25]
Dear team,

is there a helper method that could be used to wait for the Kubernetes Cluster to become available?

**Comment by gabisavu-ionos** [comment]
Hello, yes it is and is available with the new version of sdk-go(6.0.3) which will be released today.
In the client.go file there are some functions that are called: WaitForState, WaitForStateAsync, WaitForDeletion, WaitForDeletionAsync. 
I provided also some examples of how to sue it in the example directory of sdk(are named useWaitFor......) which are exactly  with a Kubernetes Cluster.

**Comment by BertR** [comment]
Thanks!
