### ISSUE TITLE
Error in WaitForStateAsync is not wrapped

### ISSUE THREAD

**Issue by avorima** [ionos-cloud/sdk-go#26]
## Description

The error in [this line](https://github.com/ionos-cloud/sdk-go/blob/master/client.go#L756=) is neither wrapped nor even formatted correctly which means that it cannot be handled.

Additionally, the `waitForStateWithChanel` has a typo and the async wait for state or deletion code has a few issues. Code execution continues past writing of the done and state channels. For example [here](https://github.com/ionos-cloud/sdk-go/blob/master/client.go#L754-L759=):

```go
if err != nil {
	ch <- StateChannel{
		"",
		fmt.Errorf("error occured when calling the fn function", err),
	}
	done <- true
        // code execution should not go past this point
}

```

This pattern is found throughout the `waitForStateWithChanel` and `waitForDeletionWithChannel` functions. `waitForDeletionWithChannel` even has a risk of NPE because the `apiResponse` that is checked for nil [here](https://github.com/ionos-cloud/sdk-go/blob/master/client.go#L850=) is then dereferenced [a few lines after it](https://github.com/ionos-cloud/sdk-go/blob/master/client.go#L857=). `waitForStateWithChanel` has the issue that it will hang when an error occurs. A message is sent to the `done` channel [here](https://github.com/ionos-cloud/sdk-go/blob/master/client.go#L758=) and eventually another gets sent [here](https://github.com/ionos-cloud/sdk-go/blob/master/client.go#L790=). This means that this function will never exit since the exit condition `done` is checked on the next iteration and write to the `done` channel is blocked by it's size of 1.

This can be prevent by simply adding some `continue`s or using an `else` block.

See: https://go.dev/play/p/0ENsyvFU4Bf

The code looks auto-generated so I don't know if I should contribute a patch. Please let me know.

**Comment by gabisavu-ionos** [comment]
Hello, thanks for noticing I will take a look into it.

**Comment by Ntr0** [comment]
Please note that the missing error wrapping affects all Wait* methods.

**Comment by gabisavu-ionos** [comment]
can you be more specific, please? Are you referring to the fact that the error should be a specific type of error to figure out what type of error is? and from where that error was thrown?

**Comment by gabisavu-ionos** [comment]
The bug was solved and the new implementation will be able in the next release.
If anybody want to contribute to the sdk go, I think is ok to open a pull request to the sdk-go, and I will add the code in the files that are generating the sdk.

**Comment by avorima** [comment]
@gabisavu-ionos  The issue still isn't resolved in the current master. When will the next release land?

**Comment by gabisavu-ionos** [comment]
The release is not made yet, I'm not sure when the release will be made, but I can inform you through a comment here or a message on chat.

**Comment by avorima** [comment]
Could we keep this issue open until the fix is done?

**Comment by gabisavu-ionos** [comment]
yes, sure

**Comment by piepmatz** [comment]
Can be closed as https://github.com/ionos-cloud/sdk-go/releases/tag/v6.1.2 is out, I guess.

**Comment by avorima** [comment]
The release also has issues but at least it addressed the ones mentioned here.
