### ISSUE TITLE
6.0.5851 tag is available on the official Go proxy but not on this repository

### ISSUE THREAD

**Issue by mx-psi** [ionos-cloud/sdk-go#27]
## Description

The `6.0.5851` tag is available on the official Go proxy but not on this repository. This causes issues for developers that don't use the official Go proxy. The tag should be added back on the original commit if possible, and the version `retract`ed instead.

## Expected behavior

Any tag available on the official Go proxy should also be available on this repository

## Environment

The relevant information is the `GOPROXY` value. It can be reproduced if the value is `GOPROXY=direct`. 

## How to Reproduce

List the available versions for this module both with and without using the official proxy:

With the proxy:
```
❯ GOPROXY="https://proxy.golang.org,direct" go list -m -versions github.com/ionos-cloud/sdk-go/v6
github.com/ionos-cloud/sdk-go/v6 v6.0.0-beta.1 v6.0.0-beta.2 v6.0.0-beta.3 v6.0.0-beta.4 v6.0.0-beta.5 v6.0.0-beta.6 v6.0.0-beta.7 v6.0.0-beta.8 v6.0.0-beta.9 v6.0.0 v6.0.1 v6.0.2 v6.0.3 v6.0.4 v6.0.5851
```

Without the proxy:
```
❯ GOPROXY="direct" go list -m -versions github.com/ionos-cloud/sdk-go/v6
github.com/ionos-cloud/sdk-go/v6 v6.0.0-beta.1 v6.0.0-beta.2 v6.0.0-beta.3 v6.0.0-beta.4 v6.0.0-beta.5 v6.0.0-beta.6 v6.0.0-beta.7 v6.0.0-beta.8 v6.0.0-beta.9 v6.0.0 v6.0.1 v6.0.2 v6.0.3 v6.0.4
```

## Additional Notes

It is impossible to remove the module from the Go proxy, so the correct approach is to 
1. re-publish the tag on the same commit and
2. release a new 6.x version that includes a [`retract` directive](https://go.dev/ref/mod#go-mod-file-retract) for the bad version. 

Otherwise, this will break people's builds, and automatic dependency management tools may still see the bad version and suggest upgrading to it.

**Comment by cristiGuranIonos** [comment]
Should be retracted with the new version. Will re-publish the old version also on the repo.

**Comment by mx-psi** [comment]
Thanks @cristiGuranIonos! 🙇
