### ISSUE TITLE
GenericOpenAPIError constructors and/or field setters

### ISSUE THREAD

**Issue by avorima** [ionos-cloud/sdk-go#3]
### Current SDK Version

```
v5.2.0
```

### Use-cases

For testing purposes it'd be nice to be able to create `GenericOpenAPIError` structs with a specific `Error` as model, but since all fields are private it's not possible to do this outside of this package.

### Proposal

I propose two possible solutions:

1. Change code generation to either make the fields public or provide setters
2. Add constructor(s), e.g. `NewGenericOpenAPIError(message string, body []byte, model interface{})`

I would assume that the second option is easier to implement.

**Comment by cristiGuranIonos** [comment]
Would it be useful to add a setter and the ability to set it in the constructor for statusCode also?

**Comment by cristiGuranIonos** [comment]
Should be fixed in [6.1.0](https://github.com/ionos-cloud/sdk-go/releases/tag/v6.1.0)
