### ISSUE TITLE
Add k8s cluster fields for private node pools feature

### ISSUE THREAD

**Issue by avorima** [ionos-cloud/sdk-go#32]
### Current SDK Version

```
v6.1.7
```

### Use-cases

The SDK needs to support the upcoming private node pools feature to allow tools like ionosctl or terraform to create private node pools.

### Proposal

The cloud API accepts the following new k8s cluster fields:

* `location`: string
* `natGatewayIp`: string
* `nodeSubnet`: string
* `public`: boolean

### References

https://api.ionos.com/docs/cloud/v6/#tag/Kubernetes/operation/k8sPost

**Comment by cristiGuranIonos** [comment]
Done in https://github.com/ionos-cloud/sdk-go/releases/tag/v6.1.11
